#!/bin/bash

# Set Icon
ICON=""
LINE="$(nmcli -t con show --active)"
INTERFACE="$(echo "$LINE" | grep ethernet | cut -d':' -f4)"
if [ -z "$INTERFACE" ]; then
    # Ethernet is down
    COLOR="#4f5b66"
else
    # Get link status
    STATUS=$(cat /sys/class/net/${INTERFACE}/operstate)
    # Set Color
    if [ $STATUS == "down" ] ; then
        COLOR="#4f5b66"
    elif [ $STATUS == "up" ] ; then
        if [ $ONLINE == "yes" ] ; then
            COLOR="#a3be8c"
        else
            COLOR="#ebcb8b"
        fi
    fi
    IP="$(nmcli -t device show "$INTERFACE" | grep IP4.ADDRESS | cut -d':' -f2 | cut -d'/' -f1)"
fi

echo $ICON $IP  # Full text label
echo $ICON      # Short text label (Used when status line gets too long)
echo $COLOR     # Label color
