#!/bin/bash

STEP="5"

#------------------------------------------------------------------------

volume() {
  local muted=$(pamixer --get-mute)
  local percent=$(pamixer --get-volume)

  if [ "$muted" == "true" ]; then
    echo "Muted"
  else
    echo "$percent%"
  fi
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) pamixer --toggle-mute ;;  # right click, mute/unmute
  4) pamixer --increase ${STEP} ;; # scroll up, increase
  5) pamixer --decrease ${STEP} ;; # scroll down, decrease
esac

volume
